declare module "trello-card-api" {
    // Generated by https://quicktype.io

    export interface ITrelloCard {
        id: string;
        checkItemStates: null;
        closed: boolean;
        dateLastActivity: string;
        desc: string;
        descData: null;
        dueReminder: null | number;
        idBoard: string;
        idList: string;
        idMembersVoted: any[];
        idShort: number;
        idAttachmentCover: null;
        idLabels: any[];
        manualCoverAttachment: boolean;
        name: string;
        pos: number;
        shortLink: string;
        isTemplate: boolean;
        cardRole: null;
        badges: Badges;
        dueComplete: boolean;
        due: null | string;
        idChecklists: string[];
        idMembers: any[];
        labels: any[];
        shortUrl: string;
        start: null | string;
        subscribed: boolean;
        url: string;
        cover: Cover;
    }

    export interface Badges {
        attachmentsByType: AttachmentsByType;
        location: boolean;
        votes: number;
        viewingMemberVoted: boolean;
        subscribed: boolean;
        fogbugz: string;
        checkItems: number;
        checkItemsChecked: number;
        checkItemsEarliestDue: null;
        comments: number;
        attachments: number;
        description: boolean;
        due: null;
        dueComplete: boolean;
        start: null;
    }

    export interface AttachmentsByType {
        trello: Trello;
    }

    export interface Trello {
        board: number;
        card: number;
    }

    export interface Cover {
        idAttachment: null;
        color: null | string;
        idUploadedBackground: null;
        size: string;
        brightness: string;
        idPlugin: null;
    }

}