// Generated by https://quicktype.io
declare module "trello-attachment-response" {
    export interface ITrelloAttachmentResponse {
        id: string;
        bytes: number;
        date: string;
        edgeColor: string;
        idMember: string;
        isUpload: boolean;
        mimeType: "image/jpeg" | string;
        name: string;
        previews: Preview[];
        url: string;
        pos: number;
        fileName: string;
    }

    export interface Preview {
        id: string;
        _id: string;
        scaled: boolean;
        url: string;
        bytes: number;
        height: number;
        width: number;
    }
}