declare module "trello-api" {
    // Generated by https://quicktype.io

    export interface ITrelloBoard {
        name: string;
        desc: string;
        descData: null;
        closed: boolean;
        idOrganization: string |null;
        idEnterprise: null;
        limits: null;
        pinned: null;
        shortLink: string;
        powerUps: any[];
        dateLastActivity: null;
        idTags: any[];
        datePluginDisable: null;
        creationMethod: string;
        ixUpdate: null;
        enterpriseOwned: boolean;
        idBoardSource: null;
        idMemberCreator: string;
        id: string;
        starred: null;
        url: string;
        prefs: Prefs;
        subscribed: boolean;
        labelNames: LabelNames;
        shortUrl: string;
        templateGallery: null;
        premiumFeatures: any[];
        memberships: Membership[];
    }

    export interface LabelNames {
        green: string;
        yellow: string;
        orange: string;
        red: string;
        purple: string;
        blue: string;
        sky: string;
        lime: string;
        pink: string;
        black: string;
    }

    export interface Membership {
        id: string;
        idMember: string;
        memberType: string;
        unconfirmed: boolean;
    }

    export interface Prefs {
        permissionLevel: string;
        hideVotes: boolean;
        voting: string;
        comments: string;
        invitations: string;
        selfJoin: boolean;
        cardCovers: boolean;
        isTemplate: boolean;
        cardAging: string;
        calendarFeedEnabled: boolean;
        background: string;
        backgroundImage: null;
        backgroundImageScaled: null;
        backgroundTile: boolean;
        backgroundBrightness: string;
        backgroundColor: string;
        backgroundBottomColor: string;
        backgroundTopColor: string;
        canBePublic: boolean;
        canBeEnterprise: boolean;
        canBeOrg: boolean;
        canBePrivate: boolean;
        canInvite: boolean;
    }

}