declare module "trello-card-api" {
    // Generated by https://quicktype.io

    export interface ITCardInfo {
        id: string;
        idMemberCreator: string;
        data: Data;
        type: string;
        date: string;
        limits: Limits;
        appCreator: AppCreator;
        memberCreator: MemberCreator;
    }

    export interface AppCreator {
        id: string;
    }

    export interface Data {
        text: string;
        card: Ard;
        board: Ard;
        list: List;
    }

    export interface Ard {
        id: string;
        name: string;
        shortLink: string;
        idShort?: number;
    }

    export interface List {
        id: string;
        name: string;
    }

    export interface Limits {
        reactions: Reactions;
    }

    export interface Reactions {
        perAction: PerAction;
        uniquePerAction: PerAction;
    }

    export interface PerAction {
        status: string;
        disableAt: number;
        warnAt: number;
    }

    export interface MemberCreator {
        id: string;
        username: string;
        activityBlocked: boolean;
        avatarHash: null;
        avatarUrl: null;
        fullName: string;
        idMemberReferrer: string;
        initials: string;
        nonPublic: NonPublic;
        nonPublicAvailable: boolean;
    }

    export interface NonPublic {
    }

}