declare module "trello-list-api" {
    // Generated by https://quicktype.io

    export interface ITrelloList {
        id: string;
        name: string;
        closed: boolean;
        pos: number;
        softLimit: null;
        idBoard: string;
        subscribed: boolean;
    }

}