declare module "trello-label-api" {
    // Generated by https://quicktype.io

    export interface ITrelloLabel {
        id: string;
        idBoard: string;
        name: string;
        color: string;
    }

}